package com.sentinel.app.accessibility

import android.content.Context
import android.graphics.PixelFormat
import android.graphics.drawable.GradientDrawable
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.text.method.LinkMovementMethod
import android.util.Log
import android.util.TypedValue
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import android.widget.Button
import android.widget.FrameLayout
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import com.sentinel.app.R
import com.sentinel.app.analysis.Verdict

/**
 * Owns the system-wide overlay shown by [SentinelAccessibilityService]
 * when a URL is flagged as MALICIOUS / SUSPICIOUS.
 *
 * Lifecycle:
 *  - The first call to [show] adds a single fullscreen FrameLayout to
 *    the WindowManager; subsequent calls replace its contents.
 *  - [hide] removes the view if attached. Idempotent.
 *  - The service MUST call [hide] in onUnbind/onDestroy to avoid the
 *    "View not attached to window manager" leak.
 *
 * Touch model:
 *  - Background dim is non-modal: tapping outside the card dismisses
 *    the overlay (delivered as a press on the root FrameLayout).
 *  - The card itself eats touches so swipes inside it don't dismiss.
 *
 * The overlay is built procedurally rather than from an inflated XML
 * resource because resource inflation in an AccessibilityService runs
 * with the *application* theme (not an Activity theme), and we want
 * to be sure the dim background works regardless of host configuration.
 */
class OverlayManager private constructor(private val appContext: Context) {

    private val windowManager: WindowManager =
        appContext.getSystemService(Context.WINDOW_SERVICE) as WindowManager
    private val handler = Handler(Looper.getMainLooper())

    @Volatile
    private var hostView: FrameLayout? = null

    /**
     * Callback installed by the service so that "Torna indietro" can
     * trigger `performGlobalAction(GLOBAL_ACTION_BACK)` after the
     * overlay is removed. The service overwrites the previous binder
     * on every show — only the last submitted URL matters.
     */
    @Volatile
    private var onBackRequested: (() -> Unit)? = null

    /**
     * Package name of the browser that triggered the currently shown
     * overlay. Used by [SentinelAccessibilityService] to auto-dismiss
     * the overlay when the user navigates away from that package.
     * Null when no overlay is on screen.
     */
    @Volatile
    private var owningPackage: String? = null

    /**
     * Wall-clock timestamp when the current overlay was attached.
     * The accessibility service uses this to honour a short grace
     * period after [show], during which package-change events do not
     * trigger an auto-dismiss. Without the grace period the overlay
     * would be killed almost immediately by transient STATE_CHANGED
     * events generated by the WindowManager during the attach
     * animation, by our own package (the overlay window itself
     * raises a STATE_CHANGED with our app's package name), or by
     * com.android.systemui during the back transition.
     */
    @Volatile
    private var shownAtMs: Long = 0L

    fun currentOverlayPackage(): String? = owningPackage

    /**
     * Returns true if the overlay is still inside its post-show grace
     * window and therefore should NOT be auto-dismissed on a package
     * change. Caller passes `System.currentTimeMillis()`.
     */
    fun shouldRetainOnPackageChange(nowMs: Long): Boolean {
        if (owningPackage == null) return false
        return nowMs - shownAtMs < AUTO_DISMISS_GRACE_MS
    }

    /**
     * Show or refresh the overlay. Safe to call from any thread; the
     * actual WindowManager mutation is posted to the main looper.
     */
    fun show(
        url: String,
        verdict: Verdict,
        reasons: List<String>,
        owningPackage: String?,
        onBack: () -> Unit,
    ) {
        if (!AccessibilityHelper.canDrawOverlays(appContext)) {
            handler.post {
                Toast.makeText(appContext, R.string.overlay_permission_missing, Toast.LENGTH_LONG)
                    .show()
            }
            return
        }
        handler.post {
            onBackRequested = onBack
            this.owningPackage = owningPackage
            shownAtMs = System.currentTimeMillis()
            ensureHostView()
            renderContent(url, verdict, reasons)
        }
    }

    fun hide() {
        handler.post {
            owningPackage = null
            detach()
        }
    }

    /** Builds the root FrameLayout (dim background) and attaches it once. */
    private fun ensureHostView() {
        if (hostView != null) return
        val root = FrameLayout(appContext).apply {
            setBackgroundColor(DIM_BACKGROUND_COLOR)
            setOnClickListener { detach() }
            alpha = 0f
            isClickable = true
            isFocusable = true
        }
        val lp = buildLayoutParams()
        try {
            windowManager.addView(root, lp)
            hostView = root
            root.animate().alpha(1f).setDuration(FADE_IN_MS).start()
        } catch (error: Exception) {
            Log.w(TAG, "Failed to attach overlay; missing draw-overlay permission?", error)
            hostView = null
        }
    }

    /** Replaces the card content; assumes [hostView] is attached. */
    private fun renderContent(url: String, verdict: Verdict, reasons: List<String>) {
        val root = hostView ?: return
        root.removeAllViews()
        val card = buildCard(url, verdict, reasons)
        root.addView(card, FrameLayout.LayoutParams(
            FrameLayout.LayoutParams.MATCH_PARENT,
            FrameLayout.LayoutParams.WRAP_CONTENT,
        ).apply {
            gravity = Gravity.CENTER
            val side = dp(20)
            setMargins(side, side, side, side)
        })
    }

    private fun detach() {
        val view = hostView ?: return
        // Clear the ownership marker eagerly so any STATE_CHANGED
        // event the AccessibilityService receives during the fade-out
        // does not re-trigger a hide() on the already-dying overlay.
        owningPackage = null
        view.animate()
            .alpha(0f)
            .setDuration(FADE_OUT_MS)
            .withEndAction {
                runCatching { windowManager.removeView(view) }
                if (hostView === view) hostView = null
            }
            .start()
    }

    private fun buildCard(
        url: String,
        verdict: Verdict,
        reasons: List<String>,
    ): View {
        val accent = if (verdict == Verdict.MALICIOUS) {
            0xFFD32F2F.toInt() // danger red
        } else {
            0xFFF9A825.toInt() // warning amber
        }
        val onSurface = 0xFF1F1F1F.toInt()
        val onSurfaceVariant = 0xFF555555.toInt()

        val card = LinearLayout(appContext).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(dp(20), dp(20), dp(20), dp(20))
            background = GradientDrawable().apply {
                cornerRadius = dp(16).toFloat()
                setColor(0xFFFFFFFF.toInt())
            }
            // Eat touches so taps inside the card don't dismiss the overlay.
            isClickable = true
        }

        // Title row: shield icon + bold "Attenzione".
        val titleRow = LinearLayout(appContext).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
        }
        val icon = ImageView(appContext).apply {
            setImageResource(R.drawable.ic_sentinel_notification)
            setColorFilter(accent)
            layoutParams = LinearLayout.LayoutParams(dp(28), dp(28))
        }
        val title = TextView(appContext).apply {
            text = appContext.getString(R.string.overlay_danger_title)
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 20f)
            setTextColor(accent)
            setPadding(dp(10), 0, 0, 0)
            setTypeface(typeface, android.graphics.Typeface.BOLD)
        }
        titleRow.addView(icon)
        titleRow.addView(title)
        card.addView(titleRow)

        // Subtitle.
        card.addView(TextView(appContext).apply {
            text = appContext.getString(R.string.overlay_danger_subtitle)
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 14f)
            setTextColor(onSurfaceVariant)
            setPadding(0, dp(8), 0, 0)
            movementMethod = LinkMovementMethod.getInstance()
        })

        // URL in monospace.
        card.addView(TextView(appContext).apply {
            text = url
            setTextSize(TypedValue.COMPLEX_UNIT_SP, 13f)
            setTextColor(onSurface)
            typeface = android.graphics.Typeface.MONOSPACE
            setPadding(0, dp(12), 0, 0)
            setTextIsSelectable(true)
            maxLines = 3
            ellipsize = android.text.TextUtils.TruncateAt.END
        })

        // Reasons header + list.
        if (reasons.isNotEmpty()) {
            card.addView(TextView(appContext).apply {
                text = appContext.getString(R.string.overlay_reasons_header)
                setTextSize(TypedValue.COMPLEX_UNIT_SP, 13f)
                setTextColor(onSurfaceVariant)
                setPadding(0, dp(14), 0, dp(4))
                setTypeface(typeface, android.graphics.Typeface.BOLD)
            })
            reasons.take(MAX_REASONS_SHOWN).forEach { reason ->
                card.addView(TextView(appContext).apply {
                    text = "•  $reason"
                    setTextSize(TypedValue.COMPLEX_UNIT_SP, 13f)
                    setTextColor(onSurface)
                    setPadding(0, dp(2), 0, dp(2))
                })
            }
        }

        // Action row.
        val actions = LinearLayout(appContext).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.END
            setPadding(0, dp(16), 0, 0)
        }
        val proceed = Button(appContext).apply {
            text = appContext.getString(R.string.overlay_danger_proceed)
            isAllCaps = false
            setTextColor(onSurfaceVariant)
            background = null
            setOnClickListener { showProceedConfirm() }
        }
        val back = Button(appContext).apply {
            text = appContext.getString(R.string.overlay_danger_back)
            isAllCaps = false
            setTextColor(0xFFFFFFFF.toInt())
            background = GradientDrawable().apply {
                cornerRadius = dp(8).toFloat()
                setColor(accent)
            }
            setPadding(dp(20), dp(10), dp(20), dp(10))
            setOnClickListener { triggerBack() }
        }
        actions.addView(proceed)
        actions.addView(back, LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.WRAP_CONTENT,
            LinearLayout.LayoutParams.WRAP_CONTENT,
        ).apply { leftMargin = dp(8) })
        card.addView(actions)
        return card
    }

    private fun triggerBack() {
        // Remove the overlay view *immediately* (no fade animation):
        // until removeView returns, our window still owns focus and a
        // GLOBAL_ACTION_BACK fired during the fade-out would be
        // consumed by us instead of being routed to the underlying
        // browser. The fade was visually nicer but produced bug B
        // ("Torna indietro" did nothing) reported on 2026-05-15.
        val cb = onBackRequested
        onBackRequested = null
        owningPackage = null
        val view = hostView
        if (view != null) {
            view.animate().cancel()
            runCatching { windowManager.removeView(view) }
            hostView = null
        }
        // Give the window manager a moment to switch focus back to
        // the browser before asking AccessibilityService to issue
        // GLOBAL_ACTION_BACK.
        handler.postDelayed({ cb?.invoke() }, BACK_ACTION_DELAY_MS)
    }

    private fun showProceedConfirm() {
        // We do not build a second overlay for a confirm dialog —
        // accessibility-service overlays cannot host modal dialogs
        // attached to an Activity. Instead we let the user dismiss the
        // current overlay; the underlying browser remains showing the
        // dangerous URL, which is exactly the documented "Procedi
        // comunque" semantics: the user keeps going, we step out of the
        // way. A brief toast acknowledges the choice.
        Toast.makeText(appContext, R.string.overlay_danger_proceed_toast, Toast.LENGTH_SHORT).show()
        detach()
    }

    private fun buildLayoutParams(): WindowManager.LayoutParams {
        val type = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
        } else {
            @Suppress("DEPRECATION")
            WindowManager.LayoutParams.TYPE_PHONE
        }
        return WindowManager.LayoutParams(
            WindowManager.LayoutParams.MATCH_PARENT,
            WindowManager.LayoutParams.MATCH_PARENT,
            type,
            // FLAG_NOT_FOCUSABLE is critical here: it lets the
            // overlay sit on top of the browser visually while
            // letting the AccessibilityService's
            // performGlobalAction(GLOBAL_ACTION_BACK) reach the
            // browser instead of being consumed by our own window.
            // This is what allows us to show the overlay FIRST and
            // then issue the back action silently underneath.
            // FLAG_NOT_FOCUSABLE implies FLAG_NOT_TOUCH_MODAL — that
            // is fine: taps outside the card dismiss the overlay via
            // setOnClickListener on the root, taps inside are still
            // received by buttons.
            WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN or
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED or
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
            PixelFormat.TRANSLUCENT,
        ).apply {
            gravity = Gravity.CENTER
        }
    }

    private fun dp(value: Int): Int {
        val density = appContext.resources.displayMetrics.density
        return (value * density + 0.5f).toInt()
    }

    companion object {
        private const val TAG = "OverlayManager"
        private const val DIM_BACKGROUND_COLOR = 0x66000000 // 0.4 alpha black
        private const val FADE_IN_MS = 200L
        private const val FADE_OUT_MS = 150L
        private const val BACK_ACTION_DELAY_MS = 50L
        private const val MAX_REASONS_SHOWN = 4
        // Grace window after show(): any package-change event in this
        // interval is ignored by the auto-dismiss logic. Tuned so
        // that the WindowManager attach + Chrome back transition
        // animations finish before we react to package changes.
        private const val AUTO_DISMISS_GRACE_MS = 1_500L

        @Volatile
        private var instance: OverlayManager? = null

        fun get(context: Context): OverlayManager {
            val existing = instance
            if (existing != null) return existing
            return synchronized(this) {
                instance ?: OverlayManager(context.applicationContext).also { instance = it }
            }
        }
    }
}
